name: Build

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  build:
    uses: lumentae/actions/.github/workflows/build-cpp.yml@main
    with:
      python_packages: meson
      system_packages: libsystemd-dev qt6-base-dev qt6-declarative-dev qt6-tools-dev
  release:
    permissions:
      contents: write
    needs: build
    uses: lumentae/actions/.github/workflows/release.yml@main